name: Daily Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 17 * * *'  # Runs daily at 18:00 UTC

  workflow_dispatch:  # Allows manual trigger

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update content
        run: | # python
          python hw.py

      - name: hariharan.chandran@straive.com
        run: |
          git config --global user.name "Daily Commit"
          git config --global user.email "hariharan.chandran@straive.com"
          git add *.txt
          git commit -m "Automated daily commit - $(date)" || exit 0
          git push
